### ISSUE TITLE
Exercise4 input file

### ISSUE THREAD

**Issue by iadamo1** [pgugger/LandscapeGenomicsWorkshop_Morelia#1]
Hi, 
I was looking at your tutorial for the exercise 4 and I was wondering if you standardized the all the explanatory variables in order to run the variation partitioning test. 
thanks a lot for your answer.

**Comment by pgugger** [comment]
Yes, I generally scale and center explanatory variables when running RDA. I believe that the rda function does this by default, but if not, there are options to specify these.

**Comment by iadamo1** [comment]
Thanks a lot,
I I was not sure about scaling and centering  also the latitude and
longitude, since I am new to these analyses.
Anyway I found the explanations in your tutorial very useful.

Il giorno mer 24 gen 2018 alle 20:51 Paul Gugger <notifications@github.com>
ha scritto:
